[package]
name = "cp-express-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
circuit_playground_express = "0.11.1"
panic-halt = "1.0.0"
smart-leds = "0.3.0"
smart-leds-trait = "0.3.0"
ws2812-timer-delay = { version = "0.3.0", features = ["slow"] }
